### ISSUE TITLE
Android Version

### ISSUE THREAD

**Issue by SeeMengShen** [MyLegGuy/GrowtopiaMusicSimulatorFinal#1]
I got no idea how to save and load a file in the Android version and it looks like there is a problem with the hotkey stuff lol

**Comment by SeeMengShen** [comment]
When I save file it just says "Failed to open file" and sdcard/GMSF/[The file name I typed]

**Comment by SeeMengShen** [comment]
Can you provide me a actual file name  format to load a file like ABC.angrylegguy or ABC.GMSF

**Comment by SeeMengShen** [comment]
I can't find any folder called 'GMSF' in my phone. Is it supposed to be created automatically when the app is installed or I need to create one manually?

**Comment by SeeMengShen** [comment]
I

**Comment by SeeMengShen** [comment]
I found out what's the problem already 😂
It's about the app permission.😂
Thank you MyLegGuy

**Comment by throwaway9098** [comment]
It's been almost a year since the last post but please help if you can
I'm unable to alternate the song location and the app tells me to turn the storage permission on, but it's already on.
I can't find any files related to the simulator too.
I've tried clearing cache/data and reinstalling, didn't work. How do I fix this?
